project:
  type: book

book:
  site-url: https://alexander-pastukhov.github.io/learn-python-by-writing-games
  title: "Learn Python by Writing Games"
  author: "Alexander (Sasha) Pastukhov"
  date: "10/14/2024"
  chapters:
    - index.qmd
    - 00-software.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: de
    text: "Deutsch"
  - name: en
    text: "Englisn"
  mainlanguage: 'en'
  languages: ['de']
title-de: Lerne Python, indem du Spiele schreibst.
# description-de: description in de
author-de: Alexander (Sasha) Pastukhov
lang: en
