project:
  type: book

book:
  site-url: https://alexander-pastukhov.github.io/learn-python-by-writing-games
  title: "Learn Python by Writing Games"
  author: "Alexander (Sasha) Pastukhov"
  date: "10/14/2024"
  chapters:
    - index.qmd
    - 001-software.qmd
    - 002-programming-tips.qmd
    - 01-basics.qmd
    - 02-guess-the-number-single-round.qmd
    - 03-guess-the-number-multi-round.qmd
    - 04-guess-the-number-ai.qmd
    - 05-psychopy.qmd
    - 06-whack-a-mole.qmd
    - 07-memory.qmd
    - 08-christmas.qmd
    - 09-flappy-bird.qmd
    - 10-guitar-hero.qmd

# bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - custom.scss

babelquarto:
  languagelinks: sidebar
  languagecodes:
  - name: de
    text: "Deutsch"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['de']
title-de: Lerne Python, indem du Spiele schreibst.
# description-de: description in de
author-de: Alexander (Sasha) Pastukhov
lang: en
